name: Semantic Release

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger
    # No additional configuration needed

jobs:
  release:
    runs-on: ${{ matrix.os }} # Use available GitHub runners
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] # Run on multiple OSes

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
